<?php

namespace foxp2\backofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getArticlesCount()
    {
        $qb = $this->createQueryBuilder('a');
        return  $qb->select('count(a.id)')->getQuery()->getSingleScalarResult();       
    }
    
    /**
     * 
     * @param type $articles_per_page
     * @param type $offset
     * @return type
     */
    public function getAllArticlesList($articles_per_page, $offset)
    {
        $qb = $this->createQueryBuilder('a');        
            $qb->select('a');        
            $qb->setFirstResult($offset);
            $qb->setMaxResults($articles_per_page);
        return $qb->getQuery()->getResult();
    }
    
    /**
     * 
     * @param type $keyword
     * @return type
     */
    public function findArticleyByName($keyword)
    {
        $qb = $this->createQueryBuilder('a');        
            $qb->select('a');     
            $qb->andWhere($qb->expr()->like('a.articleName',  $qb->expr()->literal($keyword.'%')));
        return $qb->getQuery()->getResult();
    }
}
