<?php

namespace foxp2\backofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GistcommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GistcommentsRepository extends EntityRepository
{
    
    /**
     * 
     * @param type $articles_per_page
     * @param type $offset
     * @return type
     */
    public function getAllGistcommentsList($gistcomments_per_page, $offset)
    {
        $qb = $this->createQueryBuilder('g');        
            $qb->select('g');        
            $qb->setFirstResult($offset);
            $qb->setMaxResults($gistcomments_per_page);
        return $qb->getQuery()->getResult();
    }
}
