profil_index:
    pattern:  /
    defaults: { _controller: "foxp2backofficeBundle:Profil:index" }
profil_limit:
    pattern:  /limit
    defaults: { _controller: "foxp2backofficeBundle:Profil:getlimit" }
profil_ajax:
    pattern:  /profil/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxprofil" }
activities_ajax:
    pattern:  /activities/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxactivities" }
activity_ajax:
    pattern:  /activity/name={name}&id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxactivity"}
    requirements:
        _method:  POST        
repositories_ajax:
    pattern:  /repositories/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxrepositories" }
watched_ajax:
    pattern:  /watched/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxwatched" }
following_ajax:
    pattern:  /following/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxfollowing" }
followers_ajax:
    pattern:  /followers/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getajaxfollowers" }
gists_ajax:
    pattern:  /gists/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getgistsajax" }
gist_ajax:
    pattern:  /gist/id={id}
    defaults: { _controller: "foxp2backofficeBundle:Profil:getgistajax" }  