articles:
    pattern:  /
    defaults: { _controller: "foxp2projectsBundle:Articles:index" }

articles_show:
    pattern:  /{id}/show
    defaults: { _controller: "foxp2projectsBundle:Articles:show" }

articles_new:
    pattern:  /new
    defaults: { _controller: "foxp2projectsBundle:Articles:new" }

articles_create:
    pattern:  /create
    defaults: { _controller: "foxp2projectsBundle:Articles:create" }
    requirements: { _method: post }

articles_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "foxp2projectsBundle:Articles:edit" }

articles_update:
    pattern:  /{id}/update
    defaults: { _controller: "foxp2projectsBundle:Articles:update" }
    requirements: { _method: post|put }

articles_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "foxp2projectsBundle:Articles:delete" }
    requirements: { _method: post|delete }
